In [47]:
'''import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('TkAgg')
from matplotlib import pyplot as plt
from typing import List, Tuple, Any, Dict
from mcbo.optimizers.bo_builder import BoBuilder
from mcbo.tasks.task_base import TaskBase
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()


df = pd.read_csv('train.csv')
print(df.shape)
df = df.dropna(subset=['Age', 'Fare', 'Sex'])
target_var = df.Survived
print(df.shape)

df = df[['Sex','Age', 'Fare']]
encode_cat_var = pd.get_dummies(df['Sex'])
df = df.drop(['Sex'], axis =1)
X = pd.concat([encode_cat_var, df], axis = 1)
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns) 

y = target_var
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# Activation functions
def relu(Z):
    return np.maximum(0, Z)

def softmax(Z):
    return np.exp(Z) / np.sum(np.exp(Z))

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Loss function
def binary_cross_entropy(y_true, y_pred):
epsilon = 1e-15  # Small value to avoid numerical instability
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)  # Clip predicted probabilities to avoid taking the log of zero or one
    return -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))

    cost = np.mean(np.abs(y_true - y_pred))  # Example: Mean absolute error
    return cost

# Feed-forward ANN
def forward_prop(W1, b1, W2, b2, X_data):
    n_features = X_data.shape[1]
    if W1.shape[1] != n_features:
        W1_shape_0 = W1.size / n_features 
        W1 = np.reshape(W1_shape_0 ,n_features)
    if W2.shape[1] != W1.shape[0]:
        W2_shape_0 = W2.size / W1.shape[0]
        W2 = np.reshape((W2_shape_0, W1.shape[0]))
    Z1 = np.dot(W1, X_data.T) + b1
    A1 = relu(Z1)
    Z2 = np.dot(W2, A1) + b2
    A2 = sigmoid(Z2).T 
    return A2


# Evaluation function
def black_box_function(W1, b1, W2, b2):
    result = forward_prop(W1, b1, W2, b2, X_train)
    y_train_encoded = np.array([y_train]) # np.eye(2)[y_train]
    
    return binary_cross_entropy(y_train_encoded, result)

#class CustomTask(TaskBase):
   # @property
    #def name(self) -> str:
     #   return 'Custom Task'
    
'''
'''def evaluate(self, x: np.ndarray) -> Tuple[pd.DataFrame ,np.ndarray]:
        
        x_ind = x.iloc[1].to_numpy()  # Convert Series to NumPy array
        print("Evaluating with parameters:")
        print("x_ind:", x_ind)
        print('xind shape' , x_ind.shape)
        y[0] = black_box_function(x_ind[:16].reshape(4, 4), x_ind[16:20].reshape(4, 1), 
                                    x_ind[20:24].reshape(1, 4), x_ind[24:].reshape(1,1))
        print(y, 'yyyyyyyyyyyyyyyyy')
        return  x, y

    
    def get_search_space_params(self) -> List[Dict[str, Any]]:
        
        params = [{'name': f'W1_{i}{j}', 'type': 'num', 'lb': -1, 'ub': 1} for i in range(4) for j in range(4)]
        params.extend([{'name': f'b1_{i}', 'type': 'num', 'lb': -1, 'ub': 1} for i in range(4)])
        params.extend([{'name': f'W2_{i}{j}', 'type': 'num', 'lb': -1, 'ub': 1} for i in range(1) for j in range(4)])
        params.extend([{'name': f'b2_{i}', 'type': 'num', 'lb': -1, 'ub': 1} for i in range(1)])
        return params
        

    def get_parameter_names(self) -> List[str]:
        params = []
        for i in range(4):
            for j in range(4):
                params.append(f'W1_{i}{j}')
        params.extend([f'b1_{i}' for i in range(4)])
        for i in range(1):
            for j in range(4):
                params.append(f'W2_{i}{j}')
        params.extend([f'b2_{i}' for i in range(1)])
        return params'''
'''
# Creating task and optimization
task = TaskBase().get_search_space()
print(task, 'task')
searchspace = task.get_search_space()

epochs = 100
bo_builder = BoBuilder(model_id='gp_rd', acq_opt_id='is', acq_func_id='ei', tr_id='basic')
opt = bo_builder.build_bo(search_space=searchspace, n_init=200)


# Optimization loop
budget_eval = epochs
# Inside the optimization loop
weights_list = []
for _ in range(budget_eval):
    x_next = opt.suggest()
    print(x_next, 'easdffffffffffffffffffffffffffffffffffff')
    x_next_reshaped = np.array(x_next).reshape(1, -1)  # Reshape x_next to have shape (1, 25)
    x_next_df = pd.DataFrame(x_next_reshaped, columns=task.get_parameter_names())
    #print(x_next_reshaped, '**********************************reshaped')
    #y_next = task.evaluate(x_next_df)[1]
    #print(y_next, 'nesssssssssssssssssssssssssxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyttttttttttt')
    #weights_list.append(task.evaluate(x_next_df)[0])
    
   
    #opt.observe(x_next, y_next)
   

    
# Printing best result
print('Best parameters:', opt.best_x)
print('Best loss:', opt.best_y)

# Plotting version
fig, ax = plt.subplots(figsize=(7, 5))
y = opt.data_buffer.y.numpy()
regret_y = np.min(np.cumsum(y, axis=1), axis=0)
#plt.plot(np.arange(1,  budget_eval ), regret_y)
#plt.show()'''

"\n# Creating task and optimization\ntask = TaskBase().get_search_space()\nprint(task, 'task')\nsearchspace = task.get_search_space()\n\nepochs = 100\nbo_builder = BoBuilder(model_id='gp_rd', acq_opt_id='is', acq_func_id='ei', tr_id='basic')\nopt = bo_builder.build_bo(search_space=searchspace, n_init=200)\n\n\n# Optimization loop\nbudget_eval = epochs\n# Inside the optimization loop\nweights_list = []\nfor _ in range(budget_eval):\n    x_next = opt.suggest()\n    print(x_next, 'easdffffffffffffffffffffffffffffffffffff')\n    x_next_reshaped = np.array(x_next).reshape(1, -1)  # Reshape x_next to have shape (1, 25)\n    x_next_df = pd.DataFrame(x_next_reshaped, columns=task.get_parameter_names())\n    #print(x_next_reshaped, '**********************************reshaped')\n    #y_next = task.evaluate(x_next_df)[1]\n    #print(y_next, 'nesssssssssssssssssssssssssxxxxxxxxxxxxxxxxxxxxxxxxxyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyttttttttttt')\n    #weights_list.append(task.evaluate(x_next_df)[0])\n    \

In [48]:
#opt.suggest()

In [49]:
'''import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('TkAgg')
from matplotlib import pyplot as plt
from typing import List, Tuple, Any, Dict
from mcbo.optimizers.bo_builder import BoBuilder
from mcbo.tasks.task_base import TaskBase
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()


df = pd.read_csv('train.csv')
print(df.shape)
df = df.dropna(subset=['Age', 'Fare', 'Sex'])
target_var = df.Survived
print(df.shape)

df = df[['Sex','Age', 'Fare']]
encode_cat_var = pd.get_dummies(df['Sex'])
df = df.drop(['Sex'], axis =1)
X = pd.concat([encode_cat_var, df], axis = 1)
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns) 

y = target_var
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)



def label_parameters(layer_sizes):
    labels = {}
    for i in range(len(layer_sizes) - 1):
        labels[f"W{i}"] = f"{i}"
        labels[f"b{i}"] = f"{i}"
    return labels

class FeedForwardNN:
    def __init__(self, parameter_labels):
        self.parameter_labels = parameter_labels
        self.parameters = {}
        for param, label in self.parameter_labels.items():
            self.parameters[param] = None  # Initialize parameters to None

    def initialize_parameters(self):
        for param in self.parameter_labels.keys():
            # Initialize parameters randomly or with zeros, depending on your preference
            self.parameters[param] = np.random.randn(3, 3)  # Example initialization

    def forward_propagation(self, X):
        # Implement forward propagation using parameters stored in self.parameters
        pass  # Placeholder for implementation

    def train(self, X_train, y_train):
        # Placeholder for training process
        pass

# Example usage:
layer_sizes = np.array([10, 5, 3, 1])  # Example list of layer sizes
parameter_labels = label_parameters(layer_sizes)  # Using previously defined label_parameters function
nn = FeedForwardNN(parameter_labels)
#nn.initialize_parameters()  # Initialize parameters
#activations = nn.forward_propagation(X_train)
parameters =np.array(list( parameter_labels.keys()))
print((parameters))


'''

'import numpy as np\nimport pandas as pd\nimport matplotlib\nmatplotlib.use(\'TkAgg\')\nfrom matplotlib import pyplot as plt\nfrom typing import List, Tuple, Any, Dict\nfrom mcbo.optimizers.bo_builder import BoBuilder\nfrom mcbo.tasks.task_base import TaskBase\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import MinMaxScaler\n\nscaler = MinMaxScaler()\n\n\ndf = pd.read_csv(\'train.csv\')\nprint(df.shape)\ndf = df.dropna(subset=[\'Age\', \'Fare\', \'Sex\'])\ntarget_var = df.Survived\nprint(df.shape)\n\ndf = df[[\'Sex\',\'Age\', \'Fare\']]\nencode_cat_var = pd.get_dummies(df[\'Sex\'])\ndf = df.drop([\'Sex\'], axis =1)\nX = pd.concat([encode_cat_var, df], axis = 1)\nX = pd.DataFrame(scaler.fit_transform(X), columns=X.columns) \n\ny = target_var\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)\n\n\n\ndef label_parameters(layer_sizes):\n    labels = {}\n    for i in range(len(layer_sizes) - 1):\n        labels[f"

In [ ]:
 '''parameters_labels = par_labels(self.layer_sizes)
        unique_list = [item for sublist in [inner_sublist for outer_sublist in parameters_labels
                                            for inner_sublist in outer_sublist] for item in sublist]
        #print(parameters_labels[0], 'par_labels')
        par ={}
        W_pars = [item for sublist in parameters_labels[0] for item in sublist]
        par = [item.split('_')[0] for item in W_pars]
        for i in range(len(par)):
            par[i]=x[par[i]]
            print(x[par[i]])
            
        b_pars = [item for sublist in parameters_labels[1] for item in sublist]
        par = [item.split('_')[0] for item in b_pars]
        for i in range(len(par)):
            par[i]=x[i]'''

In [461]:
def par_labels(arr_layers):
    products = [arr_layers[i] * arr_layers[i + 1] for i in range(len(arr_layers) - 1)]
    W_res_layers = [f'W{i}' for i, val in enumerate(products) for _ in range(val)]
    b_res_layers = [f'b{i}' for i, val in enumerate(arr_layers[1:]) for _ in range(val)]
    
    W_sub = [W_res_layers[sum(products[:i]):sum(products[:i+1])] for i in range(len(products))]
    b_sub = [b_res_layers[sum(arr_layers[1:i]):sum(arr_layers[1:i+1])] for i in range(1,len(arr))]
    W_indices, b_indices = [], []
    for layer in range(1,len(arr_layers)):
        #print(arr[layer])
        W_ind = ([[ f'_{i}{j}' for i in range(max(arr_layers)) for j in range(arr_layers[layer])][:products[k]] for k in range(len(products)) ])[layer-1]
        b_ind =  ( [ f'_{i}' for i in range(5)  ][:arr_layers[layer]] )
        W_indices.append(W_ind)
        b_indices.append(b_ind)
    W_elements = [[elem + index for elem, index in zip(sub, indices)] for sub, indices in zip(W_sub, W_indices)]
    b_elements = [[elem + index for elem, index in zip(sub, indices)] for sub, indices in zip(b_sub, b_indices)]
    return   set(W_res_layers + b_res_layers) #W_elements, b_elements

print(par_labels([4,5,3,1]))y


{'W1', 'b2', 'W0', 'W2', 'b1', 'b0'}


In [574]:
from sklearn.model_selection import train_test_split
import numpy as np

# Example numpy array
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

# Split the data into training and testing subsets
train_data, test_data = train_test_split(data, test_size=0.2, random_state=42)

print("Training data:")
print(train_data)
print("\nTesting data:")
print(test_data)

Training data:
[[10 11 12]
 [ 1  2  3]
 [ 7  8  9]]

Testing data:
[[4 5 6]]


In [615]:
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('TkAgg')
from matplotlib import pyplot as plt
from typing import List, Tuple, Any, Dict
from mcbo.optimizers.bo_builder import BoBuilder
from mcbo.tasks.task_base import TaskBase
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()


# Example usage:
layer_sizes = np.array([4,5,3,1])  # Example list of layer sizes

from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples=700,
    n_features=4,
    n_informative=4,
    n_redundant=0,
   
    
    n_clusters_per_class=1,  # Increase the number of clusters per class
    
    
    flip_y=0.9,              # Increase noise
    class_sep=0.9,           # Reduce class separation for overlapping clusters
    random_state=24
)




'''df = pd.read_csv('train.csv')
print(df.shape)
df = df.dropna(subset=['Age', 'Fare', 'Sex'])
target_var = df.Survived
print(df.shape)

df = df[['Sex','Age', 'Fare']]
encode_cat_var = pd.get_dummies(df['Sex'])
df = df.drop(['Sex'], axis =1)
X = pd.concat([encode_cat_var, df], axis = 1)
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns) 
'''
#y = target_var
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [616]:



def par_labels(arr_layers):
    products = [arr_layers[i] * arr_layers[i + 1] for i in range(len(arr_layers) - 1)]
    W_res_layers = [f'W{i}' for i, val in enumerate(products) for _ in range(val)]
    b_res_layers = [f'b{i}' for i, val in enumerate(arr_layers[1:]) for _ in range(val)]
    W_sub = [W_res_layers[sum(products[:i]):sum(products[:i+1])] for i in range(len(products))]
    b_sub = [b_res_layers[sum(arr_layers[1:i]):sum(arr_layers[1:i+1])] for i in range(1,len(arr))]
    W_indices, b_indices = [], []
    for layer in range(1,len(arr_layers)):
        #print(arr[layer])
        W_ind = ([[ f'_{i}{j}' for i in range(max(arr_layers)) for j in range(arr_layers[layer])][:products[k]] for k in range(len(products)) ])[layer-1]
        b_ind =  ( [ f'_{i}' for i in range(5)  ][:arr_layers[layer]] )
        W_indices.append(W_ind)
        b_indices.append(b_ind)
    W_elements = [[elem + index for elem, index in zip(sub, indices)] for sub, indices in zip(W_sub, W_indices)]
    b_elements = [[elem + index for elem, index in zip(sub, indices)] for sub, indices in zip(b_sub, b_indices)]
    return W_elements, b_elements


def label_parameters(layer_sizes):
    labels = {}
    for i in range(len(layer_sizes) - 1):
        labels[f"W{i}"] = f"{i}"
        labels[f"b{i}"] = f"{i}"
    return labels

import numpy as np

def initialize_parameters(layer_sizes):
    parameters = {}
    for i in range(0, len(layer_sizes)):
        parameters[f"W{i}"] = np.random.randn(layer_sizes[i], layer_sizes[i-1]) * 0.01
        parameters[f"b{i}"] = np.zeros((layer_sizes[i], 1))
    return parameters.keys()

def parameters_dict(params_array):
    """
    Create a dictionary of parameters from an array containing weights and biases.

    Parameters:
    params_array -- array containing weights and biases in the order [W0, b0, W1, b1, ..., Wn, bn]

    Returns:
    parameters -- dictionary containing the parameters 'W0', 'b0', 'W1', 'b1', ..., 'Wn', 'bn'
    """
    num_layers = len(params_array) // 2
    parameters = {}
    for i in range(num_layers):
        parameters[f'W{i}'] = params_array[2*i]
        parameters[f'b{i}'] = params_array[2*i + 1]
    return parameters



def forward_prop(X, parameters):
    """
    Perform forward propagation through each layer of a neural network.

    Parameters:
    parameters -- dictionary containing the parameters 'W0', 'b0', 'W1', 'b1', ..., 'Wn', 'bn'
    X -- input data (numpy array) of shape (input_size, m)

    Returns:
    A -- output of the last layer
    caches -- list of tuples containing the linear and activation values for each layer
    """
    caches = []
    A = X.T
    
    num_layers = len(parameters) // 2
    for i in range(num_layers):
        W = parameters[f'W{i}']
        b = parameters[f'b{i}']
        Z = np.dot(W, A) + b
        A = relu(Z) if i < num_layers - 1 else sigmoid(Z)
        caches.append((Z, A))

    return A.T, caches


# Activation functions
def relu(Z):
    return np.maximum(0, Z)

def sigmoid(Z):
    return 1 / (1 + np.exp(-Z))

# Example usage:
#layer_sizes = [4, 5, 3, 1]

#parameter_labels = label_parameters(layer_sizes)  # Using previously defined label_parameters function
#parameters =np.array(list( parameter_labels.keys()))
#print((parameters))



def softmax(Z):
    return np.exp(Z) / np.sum(np.exp(Z))

# Loss function
def binary_cross_entropy(y_true, y_pred):
    cost = np.mean(np.abs(y_true - y_pred))  # Example: Mean absolute error
    return cost

def generate_sizes(layer_sizes):
    sizes = []
    start_idx = 0
    for size in layer_sizes:
        end_idx = start_idx + size
        sizes.append(end_idx - start_idx)
        start_idx = end_idx
    return sizes


def black_box_function(X_data, parameters):
    result = forward_prop(X_data, parameters)[0]
    y_train_encoded = np.array([y_train]) # np.eye(2)[y_train]
    return binary_cross_entropy(y_train_encoded, result)

def blocks(layer_sizes):
    blocks_info = []
    start_idx = 0
    for i in range(len(layer_sizes) - 1):
        # Weight block
        weight_block_size = layer_sizes[i] * layer_sizes[i+1]
        weight_block = (start_idx, start_idx + weight_block_size)
        reshape_weight = (layer_sizes[i+1], layer_sizes[i])
        
        # Bias block
        bias_block = (weight_block[1], weight_block[1] + layer_sizes[i+1])
        reshape_bias = (layer_sizes[i+1], 1)
        
        blocks_info.extend([weight_block, reshape_weight, bias_block, reshape_bias])
        
        start_idx = bias_block[1]  # Update start index for next iteration
        
    slicing, reshaping = blocks_info[::2], blocks_info[1::2] 
    #print(slicing, reshaping, 'slicing reshaping')
    return slicing, reshaping




class CustomTask(TaskBase):
    def __init__(self, pars, layer_sizes):
        self.layer_sizes = layer_sizes
        self.pars = [np.array([]) for _ in range(len(layer_sizes) - 1)] #pars 
        

    @property
    def name(self) -> str:
        return 'Custom Task'
    
    def evaluate(self, x: np.ndarray) -> Tuple[pd.DataFrame ,np.ndarray]:
        slices, reshape_dims = blocks(self.layer_sizes)[0], blocks(self.layer_sizes)[1]
        y = np.zeros((len(x), 1))
        for ind in range(len(x)):
            x_ind = x.iloc[ind].to_numpy()  # Convert Series to NumPy array
            sliced_arrays = [x_ind[start:end] for start, end in slices]
            reshaped_arrays = tuple([sliced_array.reshape(shape) 
                               for sliced_array, shape in zip(sliced_arrays, reshape_dims)])
            y[ind] = black_box_function(X_train, parameters_dict(reshaped_arrays))
        
        return x, y, parameters_dict(reshaped_arrays)
    
    def get_search_space_params(self) -> List[Dict[str, Any]]:
        params = []
        start_idx = 0
        for layer, size in enumerate(self.layer_sizes[:-1]):
            for i in range(size):
                for j in range(self.layer_sizes[layer + 1]):
                    params.append({'name': f'W{layer}_{i}{j}', 'type': 'num', 'lb': -1, 'ub': 1})
            for i in range(self.layer_sizes[layer + 1]):
                params.append({'name': f'b{layer}_{i}', 'type': 'num', 'lb': -1, 'ub': 1})
        return params
        

    def get_parameter_names(self) -> List[str]:
        params = []
        for layer, size in enumerate(self.layer_sizes[:-1]):
            for i in range(size):
                for j in range(self.layer_sizes[layer + 1]):
                    params.append(f'W{layer}_{i}{j}')
            for i in range(self.layer_sizes[layer + 1]):
                params.append(f'b{layer}_{i}')
        return params
        
# Creating task and optimization
task = CustomTask(parameters, layer_sizes)
searchspace = task.get_search_space()

epochs = 100
bo_builder = BoBuilder(model_id='gp_rd', acq_opt_id='is', acq_func_id='ei', tr_id='basic')
opt = bo_builder.build_bo(search_space=task.get_search_space(), n_init=200)


# Optimization loop
budget_eval = epochs
# Inside the optimization loop
weights_list = []
acc_list = []

for _ in range(budget_eval):
    x_next = opt.suggest()
    
    x_next_reshaped = np.array(x_next).reshape(1, -1)  # Reshape x_next to have shape (1, 25)
    #print(task.get_parameter_names(), 'x nextttttttttt')
    x_next_df = pd.DataFrame(x_next_reshaped, columns=task.get_parameter_names())
    y_next = task.evaluate(x_next_df)[1]
    weights_list.append(task.evaluate(x_next_df)[2])
    acc_list.append(y_next)
    opt.observe(x_next, y_next)
    print(y_next)
   


# Printing best result
print('Best parameters:', opt.best_x)
print('Best loss:', opt.best_y)

# Plotting version
fig, ax = plt.subplots(figsize=(7, 5))
y = opt.data_buffer.y.numpy()
regret_y = np.min(np.cumsum(y, axis=1), axis=0)
#plt.plot(np.arange(1,  budget_eval ), regret_y)
#plt.show()

[[0.50173287]]
[[0.50618311]]
[[0.50566086]]
[[0.49962494]]
[[0.49964315]]
[[0.5011058]]
[[0.49886937]]
[[0.497183]]
[[0.49573931]]
[[0.50460659]]
[[0.498154]]
[[0.49365078]]
[[0.4968523]]
[[0.50059416]]
[[0.49716689]]
[[0.49736461]]
[[0.49777239]]
[[0.49499556]]
[[0.50288676]]
[[0.49737217]]
[[0.50282081]]
[[0.49699885]]
[[0.49380165]]
[[0.5027721]]
[[0.5001667]]
[[0.50349356]]
[[0.50180158]]
[[0.4978659]]
[[0.50058806]]
[[0.49872704]]
[[0.49771367]]
[[0.50234076]]
[[0.50470165]]
[[0.49673218]]
[[0.50152363]]
[[0.50210074]]
[[0.49946159]]
[[0.49499792]]
[[0.50360618]]
[[0.49805416]]
[[0.4953989]]
[[0.49815533]]
[[0.50320956]]
[[0.49776031]]
[[0.50176232]]
[[0.50273233]]
[[0.49770369]]
[[0.49629131]]
[[0.49894382]]
[[0.50103558]]
[[0.50412912]]
[[0.49915751]]
[[0.50133241]]
[[0.4984305]]
[[0.49962379]]
[[0.50151439]]
[[0.49685331]]
[[0.49582928]]
[[0.49992936]]
[[0.4963348]]
[[0.50531951]]
[[0.49698195]]
[[0.49703692]]
[[0.5017473]]
[[0.49879587]]
[[0.49775331]]
[[0.50095769]]
[[0.4990

In [617]:
print(acc_list.index(max(acc_list)))
print(max(acc_list))

1
[[0.50618311]]


In [618]:
weights_list

[{'W0': array([[-0.70162821, -0.48042062, -0.42378615,  0.35568254],
         [ 0.05655033, -0.8989422 ,  0.95493856, -0.65889309],
         [ 0.31474293,  0.676962  , -0.39277833,  0.22217688],
         [-0.51208734,  0.85345752,  0.24796392,  0.54194259],
         [ 0.61742338,  0.21920756, -0.52948836, -0.59668762]]),
  'b0': array([[-0.26512382],
         [-0.99483102],
         [-0.66405292],
         [ 0.86489276],
         [-0.43815777]]),
  'W1': array([[ 0.67689792, -0.36761441, -0.08037222,  0.36077328, -0.34962824],
         [ 0.45698658, -0.83359815,  0.37803429,  0.34843737, -0.76726918],
         [ 0.14132451,  0.60969829, -0.63292441,  0.77000085, -0.94054553]]),
  'b1': array([[ 0.21699535],
         [-0.56362085],
         [-0.58484639]]),
  'W2': array([[-0.35907433,  0.50187783, -0.14405586]]),
  'b2': array([[0.69723523]])},
 {'W0': array([[ 0.66808212, -0.10016516,  0.82988032,  0.14418034],
         [-0.6565914 , -0.64645708, -0.99017653,  0.56710222],
         [-

In [619]:
def binarize_outcome(res_arr):
    return np.where(res_arr<.5,0,1)

def calculate_accuracy( targets, predictions):
    """
    Calculate the accuracy between two arrays.

    Parameters:
    predictions -- numpy array containing predicted values
    targets -- numpy array containing true target values

    Returns:
    accuracy -- the accuracy between the predictions and targets
    """
    # Ensure predictions and targets have the same shape
    
    assert predictions.shape == targets.shape, "Shape mismatch between predictions and targets"

    # Count the number of correct predictions
    num_correct = np.sum(predictions == targets)

    # Calculate accuracy
    accuracy = num_correct / predictions.size

    return accuracy

def forward_prop(X, parameters):
    """
    Perform forward propagation through each layer of a neural network.

    Parameters:
    parameters -- dictionary containing the parameters 'W0', 'b0', 'W1', 'b1', ..., 'Wn', 'bn'
    X -- input data (numpy array) of shape (input_size, m)

    Returns:
    A -- output of the last layer
    caches -- list of tuples containing the linear and activation values for each layer
    """
    caches = []
    A = X.T
    
    num_layers = len(parameters) // 2
    for i in range(num_layers):
        W = parameters[f'W{i}']
        b = parameters[f'b{i}']
        Z = np.dot(W, A) + b
        A = relu(Z) if i < num_layers - 1 else sigmoid(Z)
        caches.append((Z, A))

    return A


binary_list = []
acc_list= []
for pars in weights_list:
    output = forward_prop(X_train, pars)
    #print((output.shape))
    binary_result = binarize_outcome(output)
    binary_list.append(binary_result)
    accuracy =calculate_accuracy(np.array(y_train), np.squeeze(binary_result))
    acc_list.append(accuracy)

print(max(acc_list))
print(acc_list.index(max(acc_list)))


0.5628997867803838
28


In [620]:
print(acc_list)

[0.4925373134328358, 0.4925373134328358, 0.4925373134328358, 0.4946695095948827, 0.5479744136460555, 0.47974413646055436, 0.5010660980810234, 0.509594882729211, 0.5074626865671642, 0.4925373134328358, 0.5074626865671642, 0.5074626865671642, 0.5074626865671642, 0.47547974413646055, 0.5074626865671642, 0.5181236673773987, 0.5010660980810234, 0.5074626865671642, 0.4840085287846482, 0.5031982942430704, 0.4925373134328358, 0.5074626865671642, 0.5074626865671642, 0.4904051172707889, 0.47547974413646055, 0.4925373134328358, 0.5053304904051172, 0.4904051172707889, 0.5628997867803838, 0.4840085287846482, 0.5287846481876333, 0.4925373134328358, 0.4925373134328358, 0.5138592750533049, 0.47974413646055436, 0.47121535181236673, 0.4968017057569296, 0.5074626865671642, 0.4925373134328358, 0.4989339019189765, 0.5074626865671642, 0.511727078891258, 0.4925373134328358, 0.4968017057569296, 0.4925373134328358, 0.4925373134328358, 0.5031982942430704, 0.5074626865671642, 0.47761194029850745, 0.4925373134328

In [621]:
max_acc_forw_prop = (forward_prop(X_test, weights_list[acc_list.index(max(acc_list))]))
#print(max_acc_forw_prop)
binary_max= binarize_outcome(max_acc_forw_prop)
print(calculate_accuracy(np.array(y_test), np.squeeze(binary_max)))

0.5497835497835498


In [582]:
plt.plot(y)
plt.show()

In [514]:
a1=[np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])]

print((np.array(y_train), np.squeeze(a1)))


(array([1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0

In [87]:
sizes = np.array([4, 5, 3, 1])
def blocks(layers_sizes):
    W0_block = 0,layers_sizes[0]*layers_sizes[1] # 0:20
    reshape_W0=(layers_sizes[1] ,layers_sizes[0]) # (5,4)
    b0_block = (W0_block[1], W0_block[1]+layers_sizes[1])  # 20:25
    reshape_b0 = (layers_sizes[1], 1) # (5,1)
    W1_block = (b0_block[1], b0_block[1]+ layers_sizes[1]*layers_sizes[2]) # 25: 40
    reshape_W1 = (layers_sizes[2] ,layer_sizes[1]) # (3,5)
    b1_block = (W1_block[1], W1_block[1] + layers_sizes[2] ) # 40: 43
    W2_block = (b1_block[1], b1_block[1]+ layers_sizes[2]*layers_sizes[3]) # 43: 46
    reshape_W2 = (layers_sizes[3], layers_sizes[2]) # (1,3)
    b2_block = (W2_block[1], W2_block[1]+layers_sizes[3] ) # 46:47
    
    return  [W0_block ,reshape_W0 ,b0_block ,reshape_b0 ,W1_block,reshape_W1 ,b1_block ,W2_block ,reshape_W2 ,b2_block ]
    
print(blocks(sizes))

[(0, 20), (5, 4), (20, 25), (5, 1), (25, 40), (3, 5), (40, 43), (43, 46), (1, 3), (46, 47)]


In [94]:

def blocks(layer_sizes):
    blocks_info = []
    start_idx = 0
    for i in range(len(layer_sizes) - 1):
        # Weight block
        weight_block_size = layer_sizes[i] * layer_sizes[i+1]
        weight_block = (start_idx, start_idx + weight_block_size)
        reshape_weight = (layer_sizes[i+1], layer_sizes[i])
        
        # Bias block
        bias_block = (weight_block[1], weight_block[1] + layer_sizes[i+1])
        reshape_bias = (layer_sizes[i+1], 1)
        
        blocks_info.extend([weight_block, reshape_weight, bias_block, reshape_bias])
        
        start_idx = bias_block[1]  # Update start index for next iteration
        
    slicing, reshaping = blocks_info[::2], blocks_info[1::2] 
    return slicing, reshaping

slices = blocks([4,4,1])[0]
reshapes = blocks([4,4,1])[1]

x_ind: [-0.16892534  0.45610957 -0.75662909 -0.13850915 -0.34190498  0.34915954
  0.75779161  0.16040406  0.33335724 -0.6507961  -0.91997971 -0.70209417
  0.2828864  -0.237296    0.46775188 -0.33804467  0.67510956  0.66638445
 -0.18421738 -0.22700477 -0.45617528 -0.71970609 -0.2073279  -0.89405641
 -0.6082533  -0.87080263 -0.82718392  0.66178131  0.33673016  0.54041088
 -0.59622884  0.57784119 -0.36398067  0.93459652 -0.35314288 -0.07646242
  0.22714417 -0.37265794  0.54655378  0.40279743  0.42367235 -0.64913715
  0.44843055 -0.1181024  -0.35482724  0.93855659 -0.24570666]
    


([(0, 16), (16, 20), (20, 24), (24, 25)], [(4, 4), (4, 1), (1, 4), (1, 1)])


In [97]:
import numpy as np

# Example array
my_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Example list of tuples specifying slices
slices = [(0, 3), (5, 8)]

# Slice the array according to each tuple in the list
sliced_arrays = [my_array[start:end] for start, end in slices]

# Print sliced arrays
print(sliced_arrays)


[array([1, 2, 3]), array([6, 7, 8])]


In [402]:
arr = np.array([4,5,3,1])
products = [arr[i] * arr[i + 1] for i in range(len(arr) - 1)] # [20, 15, 3]
W_res_layers = [f'W{i}' for i, val in enumerate(products) for _ in range(val)]
b_res_layers = [f'b{i}' for i, val in enumerate(arr[1:]) for _ in range(val)]
#W_res_neurons = [i + f'_']
#print(W_res_layers)
#print(b_res_layers)


def par_labels(arr_layers):
    products = [arr_layers[i] * arr_layers[i + 1] for i in range(len(arr_layers) - 1)]
    W_res_layers = [f'W{i}' for i, val in enumerate(products) for _ in range(val)]
    b_res_layers = [f'b{i}' for i, val in enumerate(arr_layers[1:]) for _ in range(val)]
    W_sub = [W_res_layers[sum(products[:i]):sum(products[:i+1])] for i in range(len(products))]
    b_sub = [b_res_layers[sum(arr_layers[1:i]):sum(arr_layers[1:i+1])] for i in range(1,len(arr))]
    W_indices, b_indices = [], []
    for layer in range(1,len(arr_layers)):
        #print(arr[layer])
        W_ind = ([[ f'_{i}{j}' for i in range(max(arr_layers)) for j in range(arr_layers[layer])][:products[k]] for k in range(len(products)) ])[layer-1]
        b_ind =  ( [ f'_{i}' for i in range(5)  ][:arr_layers[layer]] )
        W_indices.append(W_ind)
        b_indices.append(b_ind)
    W_elements = [[elem + index for elem, index in zip(sub, indices)] for sub, indices in zip(W_sub, W_indices)]
    b_elements = [[elem + index for elem, index in zip(sub, indices)] for sub, indices in zip(b_sub, b_indices)]
    return W_elements, b_elements

#print(par_labels(arr)[0])

print([item for sublist in par_labels(arr)[0] for item in sublist])
#for i in range(len(par_labels(arr[0]))): 
 #   print(par_labels(arr[0])[f"W{i}_{j}{k}"] = x[f'W{i}_{j}{k}'].values

#unique_list = [item for sublist in [inner_sublist for outer_sublist in par_labels(arr) for inner_sublist in outer_sublist] for item in sublist]
#print(unique_list)

['W0_00', 'W0_01', 'W0_02', 'W0_03', 'W0_04', 'W0_10', 'W0_11', 'W0_12', 'W0_13', 'W0_14', 'W0_20', 'W0_21', 'W0_22', 'W0_23', 'W0_24', 'W0_30', 'W0_31', 'W0_32', 'W0_33', 'W0_34', 'W1_00', 'W1_01', 'W1_02', 'W1_10', 'W1_11', 'W1_12', 'W1_20', 'W1_21', 'W1_22', 'W1_30', 'W1_31', 'W1_32', 'W1_40', 'W1_41', 'W1_42', 'W2_00', 'W2_10', 'W2_20']


In [280]:
W_sub = [W_res_layers[sum(products[:i]):sum(products[:i+1])] for i in range(len(products))]
b_sub = [b_res_layers[sum(arr[1:i]):sum(arr[1:i+1])] for i in range(1,len(arr))]

print(b_sub)
print(W_sub)


[['b0', 'b0', 'b0', 'b0', 'b0'], ['b1', 'b1', 'b1'], ['b2']]
[['W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0', 'W0'], ['W1', 'W1', 'W1', 'W1', 'W1', 'W1', 'W1', 'W1', 'W1', 'W1', 'W1', 'W1', 'W1', 'W1', 'W1'], ['W2', 'W2', 'W2']]


In [301]:
max(arr)

5

In [258]:
print([[ f'_{i}' for i in range(max(arr))  ][:arr[k+1]] for k in range(len(products)) ])

[['_0', '_1', '_2', '_3', '_4'], ['_0', '_1', '_2'], ['_0']]


In [362]:

W_indices, b_indices = [], []
for layer in range(1,len(arr)):
    #print(arr[layer])
    W_ind = ([[ f'_{i}{j}' for i in range(max(arr)) for j in range(arr[layer])  ][:products[k]] for k in range(len(products)) ])[layer-1]
    b_ind =  ( [ f'_{i}' for i in range(5)  ][:arr[layer]] )
    print(len(W_ind))
    W_indices.append(W_ind)
    b_indices.append(b_ind)
print(W_indices)#, b_indices)

20
15
5
[['_00', '_01', '_02', '_03', '_04', '_10', '_11', '_12', '_13', '_14', '_20', '_21', '_22', '_23', '_24', '_30', '_31', '_32', '_33', '_34'], ['_00', '_01', '_02', '_10', '_11', '_12', '_20', '_21', '_22', '_30', '_31', '_32', '_40', '_41', '_42'], ['_00', '_10', '_20', '_30', '_40']]


In [338]:

arr = [4, 5, 3, 1]
products = [20, 15, 12]

index_list = [
    [f'_{i}{j}' for i in range(5) for j in range(min(arr[layer], products[layer-1]))]
    for layer in range(1, len(arr))
]

print(index_list)

[['_00', '_01', '_02', '_03', '_04', '_10', '_11', '_12', '_13', '_14', '_20', '_21', '_22', '_23', '_24', '_30', '_31', '_32', '_33', '_34', '_40', '_41', '_42', '_43', '_44'], ['_00', '_01', '_02', '_10', '_11', '_12', '_20', '_21', '_22', '_30', '_31', '_32', '_40', '_41', '_42'], ['_00', '_10', '_20', '_30', '_40']]


In [208]:
'W0_00', 'W0_01', 'W0_02', 'W0_03', 'W0_04', 'W0_10', 'W0_11', 'W0_12',
       'W0_13', 'W0_14', 'W0_20', 'W0_21', 'W0_22', 'W0_23', 'W0_24', 'W0_30',
       'W0_31', 'W0_32', 'W0_33', 'W0_34', 'b0_0', 'b0_1', 'b0_2', 'b0_3',
       'b0_4', 'W1_00', 'W1_01', 'W1_02', 'W1_10', 'W1_11', 'W1_12', 'W1_20',
       'W1_21', 'W1_22', 'W1_30', 'W1_31', 'W1_32', 'W1_40', 'W1_41', 'W1_42',
       'b1_0', 'b1_1', 'b1_2', 'W2_00', 'W2_10', 'W2_20', 'b2_0'

IndentationError: unexpected indent (1440925669.py, line 2)

In [348]:
for layer in range(1,4):
    print( [ f'_{i}' for i in range(5)  ][:arr[layer]] )

['_0', '_1', '_2', '_3', '_4']
['_0', '_1', '_2']
['_0']


In [324]:
my_list = [10, 20, 30, 30, 40, 50]
number_to_find = 30

index = my_list.index(number_to_find)
print("Index of", number_to_find, ":", index)

Index of 30 : 2


In [ ]:
arra = [4,5,3,1]
def forward prop(weights_array, array_layers = arra):
def evaluate
Luca Bernecker
10:10 AM
def evaluate():
.
.
.
weights number = len(arra[0]),Len(arra[1])
def  params_search():


[[-8.89785965e-01  2.87417037e-01 -1.23541565e+00  1.37089888e+00]
 [ 9.61464906e-02  2.26732635e-01  9.82827103e-01 -1.49634199e-01]
 [ 1.72538980e+00 -1.18982123e+00 -1.76873705e+00 -2.00629283e+00]
 [-1.21613042e-01  1.86972912e-01  2.64647307e-02  6.02954072e-01]
 [-2.84179172e+00 -2.55645897e-01 -1.20615038e+00 -5.79808989e-01]
 [ 1.54886779e+00 -2.03900643e+00 -1.51865010e+00 -3.60316121e-01]
 [-5.17747842e-01  4.34284603e-01  1.10906377e+00  8.89934687e-01]
 [-3.72817578e-01  2.27282960e-01  6.77439447e-01  3.68216939e-01]
 [-1.91802154e+00 -2.18130422e+00  2.36412346e+00  2.59029812e+00]
 [-1.54360634e+00  1.15326231e+00  2.44153114e-01 -1.76666707e+00]
 [-1.44980114e+00  2.41891902e-01  8.52206598e-01  8.39089970e-01]
 [ 2.63933913e-01 -3.36385960e-01 -7.11185525e-01 -2.32140956e+00]
 [ 3.65504175e-01 -1.82303039e-01 -1.30188110e+00 -1.32220478e+00]
 [-1.08882990e+00 -7.05393583e-01  1.01600824e+00  1.41306502e+00]
 [ 1.47384279e-01  2.33576664e+00 -2.80150321e+00  1.38861474e